### ISSUE TITLE
How to crop a Mat ?!

### ISSUE THREAD

**Issue by kernelgurumeditation** [szagoruyko/torch-opencv-demos#23]
Hi, thanks for the project!,  I'm trying to crop a cv::Mat

img(cv::Rect(xMin,yMin,xMax-xMin,yMax-yMin)).copyTo(croppedImg);

How can i do this ?

Thank in advance

**Comment by shrubb** [comment]
Hi, many ways to do this.

* `cv.getRectSubPix`
* `tensor:narrow()`
* `tensor[{{xMin, xMax}, {yMin, yMax}}]`

Then use `:clone()` or `dstTensor:copy(rectTensor)`

**Comment by kernelgurumeditation** [comment]
@shrubb  Thanks for your quick answer.

the function getRectSubPix seems not be doing what I would expect, it is not cropping,  but resizing the image.

Also the in the demo age_gender,  I think that the line:
 cv.cvtColor{im2, dst=im2, code=cv.COLOR_BGR2GRAY},
is not working as it should because the im2 after this line still have color, the only way to im2  to be Gray is to:
im2= cv.cvtColor{im2, dst=im2, code=cv.COLOR_BGR2GRAY},

PS: I'm using an arm platform , but I don't think that should matter right?

Thanks!

**Comment by shrubb** [comment]
Yes, ARM should be fine.

Hm, well, according to the [documentation](http://docs.opencv.org/3.1.0/da/d54/group__imgproc__transform.html), `getRectSubPix` does not resize, it just crops a patch, which is what we want.

Indeed, that line in age_gender is wrong, thanks for nothing. This is because `dst` is 3-channel (for BGR2GRAY we would need 1 obviously). But you shouldn't both specify `dst` and grab the return value, do just one of these two.

**Comment by kernelgurumeditation** [comment]
Ok, thanks for your help, sorry for the newbie questions.

**Comment by shrubb** [comment]
You're welcome! :)
